add sha prefix to hash
codacy/git-version pull request #34
Opened 2020-09-11 15:53 UTC by paulopontesm

We can't have leading zeros

<img width="750" alt="image" src="https://user-images.githubusercontent.com/3610528/92946905-922d5d00-f457-11ea-95b9-ce7df4bf350d.png">

This fails to parse and is giving us a lot of problems on helm.

![image](https://user-images.githubusercontent.com/3610528/92946950-a40f0000-f457-11ea-98aa-a1f84b79431c.png)

2020-09-11 15:53 UTC, paulopontesm commented
Don't know how long this will live, but leaving this here: https://play.golang.org/p/bbGOH88zCXn

2020-09-11 15:54 UTC, joaocosta-codacy approved these changes

2020-09-11 15:57 UTC, andreaTP requested changes
I'm not sure we should work around a limitation of an external tool like this ...

2020-09-14 13:50 UTC, closed without merging

2023-01-14 15:30 UTC, github-killough-org commented
ha