add log-path tests
codacy/git-version pull request #37
Opened 2020-12-14 22:34 UTC by paulopontesm

2020-12-14 22:40 UTC, paulopontesm commented
Missing README

2020-12-15 14:03 UTC, DReigada requested changes

2020-12-15 14:03 UTC, DReigada commented on src/git-version.cr
> +
It would be better like this:

```suggestion
    def log_path_filter
      @log_path.empty? ? "" : "-- #{@log_path}"
    end

```

2020-12-15 15:35 UTC, DReigada requested changes

2020-12-15 15:35 UTC, DReigada commented on spec/git-version-spec.cr
> +  end
I don't see much difference between this and the previous test. Do we need both?

2020-12-15 15:35 UTC, DReigada commented on spec/git-version-spec.cr
> +  it "multirepo log-path filter (multiple dirs, multiple prefixes)" do
I think you meant:
```suggestion
  it "monorepo log-path filter (multiple dirs, multiple prefixes)" do
```

2020-12-15 17:12 UTC, DReigada approved these changes

2020-12-15 17:19 UTC, DReigada approved these changes

2020-12-15 17:44 UTC, merged