feature: Truncate branch names to avoid breaking k8s deployments
codacy/git-version pull request #67
Opened 2022-11-18 16:03 UTC by lolgab

2022-11-18 18:25 UTC, machadoit commented
I like! Would add breaking tag though

2022-11-18 21:10 UTC, bmbferreira requested changes
Hey folks! Can this be optional/parametrized?

2022-11-20 22:52 UTC, lolgab commented
> Hey folks! Can this be optional/parametrized?

Do you have a use case that requires the non-truncated normalized branch name in the tag?

2022-11-21 12:19 UTC, lolgab commented on src/main.cr
> +OptionParser.parse do |parser|
It was failing to compile since they changed it in Crystal 1

2022-11-21 12:19 UTC, machadoit approved these changes
Most of the simplifications seem great assuming that things still work! Good job!

2022-11-21 12:19 UTC, merged

2022-11-21 12:25 UTC, lolgab commented
@bmbferreira We're merging this as is. You can use the previous version if you really need this behavior, since the two versions are completely the same, except for this change. Let us know your use case if you really want the flag :)